[project]
name = "mcp-server"
version = "0.1.0"
description = "Sticky Notes MCP server for Claude and Personal Agent"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.9.0",
]
